### ISSUE TITLE
3.3.5.1 下载CDH Repository 需要帐号密码

### ISSUE THREAD

**Issue by EchoShoot** [bluishglc/bdp#8]
3.3.5.1 下载CDH Repository 需要帐号密码才能下载

**Comment by EchoShoot** [comment]
刚了解到CDH开始收费了，老师，之后咱们搭建集群有新的方案吗？感觉书上的实验当下不好做了

**Comment by bluishglc** [comment]
等我找个时间看一下哈

**Comment by qikunlun** [comment]
CDH开始收费，Ambari据说不够稳定，耿老师请问采用Ambari搭建集群后期会不会不稳定，导致维护成本会比较高么？

**Comment by wxwyes** [comment]
耿老师
3.3.5.1 下载CDH Repository 需要帐号密码才能下载
能把下载好的文件上传到github不？

**Comment by saborforly** [comment]
耿老师
我想成为数据中台方面的专家，但是我不知道路应该怎么走。
您有什么建议吗？
谢谢
